package com.innercosmos.service.impl;

import com.innercosmos.service.CapsuleEmbeddingIndexService;
import com.innercosmos.service.DataRetractionReceiptService;
import com.innercosmos.service.RetractionDerivativeCleanupService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.dao.DuplicateKeyException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.TransactionDefinition;
import org.springframework.transaction.support.TransactionTemplate;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import static com.innercosmos.service.DataRetractionReceiptService.SUBJECT_CAPSULE;
import static com.innercosmos.service.DataRetractionReceiptService.SUBJECT_DATA_USE_GRANT;

/**
 * CP-15 §2-11: the executor behind the {@code data.retracted.v1} consumer
 * ({@code DataRetractedProjectionHandler}). It walks the derivative-asset inventory
 * (docs/commercialization/ledger/derivative-asset-retraction-inventory.yml) asset by asset:
 * honest NOT_APPLICABLE rows for classes with no real surface (no object storage, no server-side
 * export persistence, unrecoverable provider copies, no long-lived caches), the real push-copy
 * deletion for {@code tb_push_delivery}, and an idempotent re-assertion of the capsule matching
 * vector erasure by REUSING {@link CapsuleEmbeddingIndexService#retireForCapsule(Long)}.
 *
 * <p>Each asset action and each result row commits in its own REQUIRES_NEW transaction: the
 * consumer runs inside the outbox completion transaction, and if a later asset fails and the
 * whole event rolls back for retry, the already-cleaned assets and every result row (including
 * FAILED ones) must stay visible — a retraction cleanup failure is never silently swallowed by
 * an outer rollback.</p>
 *
 * <p>The result table is created lazily (CREATE TABLE IF NOT EXISTS, dialect-aware like
 * {@code PushDeliveryServiceImpl}) because this class is the sole owner of the surface; the H2
 * twin uses the same MySQL-mode DDL as schema.sql, PostgreSQL gets the IDENTITY twin.</p>
 */
@Service
public class RetractionDerivativeCleanupServiceImpl implements RetractionDerivativeCleanupService {
    private static final Logger log = LoggerFactory.getLogger(RetractionDerivativeCleanupServiceImpl.class);
    public static final String RESULT_TABLE = "tb_retraction_cleanup_result";
    private static final int MAX_DETAIL = 480;

    private static final String H2_DDL = """
            CREATE TABLE IF NOT EXISTS tb_retraction_cleanup_result (
              id BIGINT AUTO_INCREMENT PRIMARY KEY,
              outbox_event_id VARCHAR(36) NOT NULL,
              receipt_id BIGINT NOT NULL,
              user_id BIGINT NOT NULL,
              asset_key VARCHAR(48) NOT NULL,
              outcome VARCHAR(24) NOT NULL,
              affected_count INT NOT NULL DEFAULT 0,
              detail VARCHAR(480),
              created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
              updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
              UNIQUE KEY uq_retraction_cleanup_event_asset (outbox_event_id, asset_key)
            )
            """;
    private static final String POSTGRES_DDL = """
            CREATE TABLE IF NOT EXISTS tb_retraction_cleanup_result (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              outbox_event_id VARCHAR(36) NOT NULL,
              receipt_id BIGINT NOT NULL,
              user_id BIGINT NOT NULL,
              asset_key VARCHAR(48) NOT NULL,
              outcome VARCHAR(24) NOT NULL,
              affected_count INT NOT NULL DEFAULT 0,
              detail VARCHAR(480),
              created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
              updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
              CONSTRAINT uq_retraction_cleanup_event_asset UNIQUE (outbox_event_id, asset_key)
            )
            """;

    private final JdbcTemplate jdbc;
    private final boolean postgres;
    private final TransactionTemplate independent;
    private final CapsuleEmbeddingIndexService capsuleEmbeddingIndexService;
    private final Object ddlLock = new Object();
    private volatile boolean tableReady;

    public RetractionDerivativeCleanupServiceImpl(JdbcTemplate jdbc,
                                                  PlatformTransactionManager transactionManager,
                                                  CapsuleEmbeddingIndexService capsuleEmbeddingIndexService) {
        this.jdbc = jdbc;
        this.postgres = detectPostgres(jdbc);
        this.capsuleEmbeddingIndexService = capsuleEmbeddingIndexService;
        // Every asset action and every result row commits on its own: the outbox completion
        // transaction around the consumer must never roll back the evidence of a finished
        // cleanup when a later asset fails.
        this.independent = new TransactionTemplate(transactionManager);
        this.independent.setPropagationBehavior(TransactionDefinition.PROPAGATION_REQUIRES_NEW);
    }

    /** Same dialect probe as JdbcOutboxRepository/PushDeliveryServiceImpl. */
    private static boolean detectPostgres(JdbcTemplate jdbc) {
        try (java.sql.Connection c = jdbc.getDataSource().getConnection()) {
            return c.getMetaData().getURL().contains(":postgresql:");
        } catch (Exception e) {
            return false;
        }
    }

    @Override
    public List<CleanupResult> cleanForRetraction(RetractionCleanupCommand command) {
        ensureResultTable();
        Map<String, CleanupResult> settled = new LinkedHashMap<>();
        for (CleanupResult prior : settledResults(command.outboxEventId())) {
            settled.put(prior.assetKey(), prior);
        }
        List<CleanupResult> results = new ArrayList<>();
        for (AssetStep step : stepsFor(command)) {
            CleanupResult prior = settled.get(step.assetKey());
            if (prior != null && !prior.failed()) {
                // Idempotent replay: this asset already settled for THIS event — skip, do not
                // re-execute and do not write a second row.
                results.add(prior);
                continue;
            }
            CleanupResult outcome;
            try {
                outcome = independent.execute(status -> step.action().run());
            } catch (RuntimeException failure) {
                // One asset failing must not block the others: record the visible failure row
                // and keep walking the inventory.
                outcome = new CleanupResult(step.assetKey(), OUTCOME_FAILED, 0, describe(failure));
            }
            persistResult(command, outcome);
            results.add(outcome);
        }
        List<String> failedAssets = results.stream().filter(CleanupResult::failed)
                .map(CleanupResult::assetKey).toList();
        if (!failedAssets.isEmpty()) {
            // Surface keys and the receipt id only — never content. Throwing sends the event
            // back through the outbox retry path; settled assets are skipped on the retry.
            throw new IllegalStateException("data.retracted.v1 derivative cleanup failed for assets "
                    + failedAssets + " (receiptId=" + command.receiptId() + "); see " + RESULT_TABLE);
        }
        return List.copyOf(results);
    }

    // ---------- the inventory, as executable steps (mirrors derivative-asset-retraction-inventory.yml) ----------

    private List<AssetStep> stepsFor(RetractionCleanupCommand command) {
        return List.of(
                new AssetStep(ASSET_CACHE, () -> notApplicable(ASSET_CACHE,
                        "无长驻缓存面：全仓无 @Cacheable/@EnableCaching/Caffeine；Redis 仅承载 TTL 瞬态数据"
                                + "（Aurora 流事件默认 PT15M、stream stage 默认 PT1M、会话 30 分钟失效、幂等/限流键），"
                                + "随 TTL 自然过期，且无按撤回主体寻址的缓存键，无物可失效")),
                new AssetStep(ASSET_OBJECT_STORAGE, () -> notApplicable(ASSET_OBJECT_STORAGE,
                        "无此资产面：全仓 grep OSS/S3/MinIO/对象存储无接入命中；语音转写仅落文本"
                                + "（tb_voice_transcription.original_text/edited_text），无媒体 blob 外置存储，无副本可删")),
                new AssetStep(ASSET_EXPORT_PACKAGE, () -> notApplicable(ASSET_EXPORT_PACKAGE,
                        "服务端无导出包持久化：UserDataExportService.build 仅在内存构建并经 HTTP 响应一次性返回"
                                + "（UserDataPortabilityController.exportPackage），不落库不落盘，无可失效服务端副本；"
                                + "用户已下载副本离台即平台不可及，属不可召回面（见 PROVIDER_COPY 口径）")),
                new AssetStep(ASSET_PUSH_COPY, () -> deleteUndeliveredPushCopies(command)),
                new AssetStep(ASSET_PROVIDER_COPY, () -> notApplicable(ASSET_PROVIDER_COPY,
                        "出站即不可召回：发往 LLM Provider 的内容无法从对方系统删除，平台侧靠事前管控"
                                + "（PROVIDER_EGRESS 授权目的、LOCAL_ONLY/NO_EXTERNAL_PROCESSING 授权范围、最小化出站）；"
                                + "站内 transcript tb_ai_interaction_log 无撤回主体映射列，不随主体级撤回删除，"
                                + "仅账户级删除时整体清理")),
                new AssetStep(ASSET_CAPSULE_MATCH_VECTOR, () -> reassertCapsuleMatchVector(command)));
    }

    /**
     * Real action: delete the user's not-yet-sent push copies ({@code tb_push_delivery.title/body}
     * are wake-intent text derived from the user's trajectory; the v1 payload carries no
     * wake-intent linkage, so the honest scope is the user's undelivered rows — withholding a
     * few extra pushes beats sending recalled text). DELIVERED rows already left the platform
     * (see PROVIDER_COPY); PROCESSING rows are mid-claim and self-resolve within their 5-minute
     * lease. DELETE is naturally idempotent: a replay affecting 0 rows records 0.
     */
    private CleanupResult deleteUndeliveredPushCopies(RetractionCleanupCommand command) {
        int deleted = jdbc.update(
                "DELETE FROM tb_push_delivery WHERE user_id=? AND status IN ('PENDING','RETRY')",
                command.userId());
        return new CleanupResult(ASSET_PUSH_COPY, OUTCOME_SUCCESS, deleted,
                deleted == 0
                        ? "无未投递（PENDING/RETRY）推送副本；已投递副本见 PROVIDER_COPY 口径（不可召回）"
                        : "删除未投递（PENDING/RETRY）推送副本；已投递副本见 PROVIDER_COPY 口径（不可召回）");
    }

    /**
     * Re-assert (not reimplement) the capsule matching-vector erasure. The owner-scoped
     * transaction already erased it synchronously and recorded the receipt; this consumer-side
     * re-assertion closes crash/replay windows for remote projections and is idempotent
     * ({@link CapsuleEmbeddingIndexService#retireForCapsule(Long)} returns 0 on a cleared capsule).
     */
    private CleanupResult reassertCapsuleMatchVector(RetractionCleanupCommand command) {
        if (!DataRetractionReceiptService.DERIVATIVE_CAPSULE_MATCH_INDEX.equals(command.derivativeType())) {
            return notApplicable(ASSET_CAPSULE_MATCH_VECTOR,
                    "derivativeType=" + command.derivativeType()
                            + " 无匹配向量语义，由属主事务内同步处置（见 DataDerivativeRegistry 对应边）");
        }
        Long capsuleId = capsuleIdFor(command);
        if (capsuleId == null) {
            if ("MEMORY".equals(command.subjectType())) {
                return notApplicable(ASSET_CAPSULE_MATCH_VECTOR,
                        "属主撤回路径已在同一事务内对每个受影响共鸣体完成 retire"
                                + "（MemoryLifecycleServiceImpl.withdrawCapsuleForForgottenMemory）；"
                                + "v1 载荷只含 memoryId 不含 capsuleId，消费者无从定位，不重复处置");
            }
            return notApplicable(ASSET_CAPSULE_MATCH_VECTOR,
                    "subjectType=" + command.subjectType() + " 无法解析 capsuleId（v1 载荷未携带）");
        }
        int erased = capsuleEmbeddingIndexService.retireForCapsule(capsuleId);
        return new CleanupResult(ASSET_CAPSULE_MATCH_VECTOR, OUTCOME_SUCCESS, erased,
                "复用 CapsuleEmbeddingIndexService.retireForCapsule(" + capsuleId + ") 幂等重断言（重放返回 0）");
    }

    /** CAPSULE events carry the capsule id directly; DATA_USE_GRANT events carry the grant id. */
    private Long capsuleIdFor(RetractionCleanupCommand command) {
        if (SUBJECT_CAPSULE.equals(command.subjectType())) {
            return command.subjectId();
        }
        if (SUBJECT_DATA_USE_GRANT.equals(command.subjectType())) {
            List<Long> ids = jdbc.queryForList(
                    "SELECT consumer_id FROM tb_data_use_grant WHERE id=?", Long.class, command.subjectId());
            return ids.isEmpty() ? null : ids.getFirst();
        }
        return null;
    }

    private static CleanupResult notApplicable(String assetKey, String reason) {
        return new CleanupResult(assetKey, OUTCOME_NOT_APPLICABLE, 0, reason);
    }

    private static String describe(RuntimeException failure) {
        String message = failure.getClass().getSimpleName();
        if (failure.getMessage() != null && !failure.getMessage().isBlank()) {
            message += ": " + failure.getMessage();
        }
        return message.length() > MAX_DETAIL ? message.substring(0, MAX_DETAIL) : message;
    }

    // ---------- result row persistence (independent of the caller's transaction) ----------

    private List<CleanupResult> settledResults(java.util.UUID outboxEventId) {
        return independent.execute(status -> jdbc.query(
                "SELECT asset_key, outcome, affected_count, detail FROM " + RESULT_TABLE
                        + " WHERE outbox_event_id=? AND outcome IN ('SUCCESS','NOT_APPLICABLE')",
                (rs, row) -> new CleanupResult(rs.getString("asset_key"), rs.getString("outcome"),
                        rs.getInt("affected_count"), rs.getString("detail")),
                outboxEventId.toString()));
    }

    private void persistResult(RetractionCleanupCommand command, CleanupResult result) {
        String detail = result.detail() == null ? "" : result.detail();
        String bounded = detail.length() > MAX_DETAIL ? detail.substring(0, MAX_DETAIL) : detail;
        try {
            independent.executeWithoutResult(status -> upsertRow(command, result, bounded));
        } catch (DuplicateKeyException raced) {
            // Two workers raced the same (event, asset): the row exists, so converge on update.
            log.warn("retraction cleanup result row raced for event {} asset {}: {}",
                    command.outboxEventId(), result.assetKey(), raced.getClass().getSimpleName());
            independent.executeWithoutResult(status -> updateRow(command, result, bounded));
        }
    }

    private void upsertRow(RetractionCleanupCommand command, CleanupResult result, String bounded) {
        int updated = updateRow(command, result, bounded);
        if (updated == 0) {
            jdbc.update("INSERT INTO " + RESULT_TABLE + " (outbox_event_id, receipt_id, user_id, "
                            + "asset_key, outcome, affected_count, detail, created_at, updated_at) "
                            + "VALUES (?,?,?,?,?,?,?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)",
                    command.outboxEventId().toString(), command.receiptId(), command.userId(),
                    result.assetKey(), result.outcome(), result.affectedCount(), bounded);
        }
    }

    private int updateRow(RetractionCleanupCommand command, CleanupResult result, String bounded) {
        return jdbc.update("UPDATE " + RESULT_TABLE + " SET outcome=?, affected_count=?, detail=?, "
                        + "updated_at=CURRENT_TIMESTAMP WHERE outbox_event_id=? AND asset_key=?",
                result.outcome(), result.affectedCount(), bounded,
                command.outboxEventId().toString(), result.assetKey());
    }

    private void ensureResultTable() {
        if (tableReady) return;
        synchronized (ddlLock) {
            if (tableReady) return;
            jdbc.execute(postgres ? POSTGRES_DDL : H2_DDL);
            tableReady = true;
        }
    }

    /** One inventory asset and its executable action (the action runs in its own transaction). */
    private record AssetStep(String assetKey, AssetAction action) {
    }

    @FunctionalInterface
    private interface AssetAction {
        CleanupResult run();
    }
}
