apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - service-account.yml
  - postgres-storage.yml
  - postgres-statefulset.yml
  - postgres-service.yml
  - redis-deployment.yml
  - redis-service.yml
  - data-network-policy.yml
  - gateway.yml
  - http-route.yml
labels:
  - includeSelectors: false
    pairs:
      inner-cosmos/profile: academy-eks
images:
  - name: inner-cosmos
    newName: inner-cosmos
    newTag: academy-placeholder
