#!/usr/bin/env bash
# Demo: build an Android APK that points at a given server URL (the tunnel URL or a hotspot LAN IP).
# Writes a throwaway, gitignored .env.demo with that URL, builds the web bundle in demo mode, syncs
# Capacitor, and assembles the debug APK. The URL must be a public HTTPS origin (the tunnel) OR a
# plain HTTP origin (hotspot) — the demo build permits both; production builds do NOT.
#
# Usage: bash scripts/demo/build-demo-apk.sh <URL>
#   e.g. bash scripts/demo/build-demo-apk.sh https://some-words.trycloudflare.com
set -euo pipefail

URL="${1:-}"
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT/web"

if [ -z "$URL" ]; then
  echo "Usage: bash scripts/demo/build-demo-apk.sh <URL>   (e.g. https://xxx.trycloudflare.com)" >&2
  exit 1
fi

# Validate it parses as an origin (scheme + host; optional port for HTTP hotspot).
PROTO="$(python -c "import sys,urllib.parse as u; print(u.urlparse(sys.argv[1]).scheme)" "$URL" 2>/dev/null || true)"
if [ "$PROTO" != "https" ] && [ "$PROTO" != "http" ]; then
  echo "ERROR: URL must start with http:// or https:// — got: $URL" >&2
  exit 1
fi

# Throwaway, gitignored demo env (the real URL changes per demo; never commit it).
cat > "$ROOT/web/.env.demo" <<EOF
# GENERATED by scripts/demo/build-demo-apk.sh — gitignored. Demo build pointing at: $URL
VITE_NATIVE_SHELL=true
VITE_DEMO_MODE=true
VITE_API_BASE_URL=$URL
VITE_API_ALLOWED_ORIGINS=$URL
EOF
echo "Wrote web/.env.demo -> $URL (gitignored)"

export JAVA_HOME="${JAVA_HOME:-/c/Program Files/Java/jdk-21.0.10}"

echo "Building web bundle (demo mode)..."
npm run build -- --mode demo

echo "Syncing Capacitor + assembling debug APK..."
npx cap sync android
( cd android && ./gradlew.bat assembleDebug ) || ( cd android && gradlew.bat assembleDebug )

APK="$ROOT/web/android/app/build/outputs/apk/debug/app-debug.apk"
echo
echo "Done. APK: $APK"
echo "Share this APK; it connects to: $URL"
