apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provisioning
  namespace: observability
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        uid: prometheus
        type: prometheus
        access: proxy
        url: http://prometheus.observability.svc:9090
        isDefault: true
        jsonData:
          exemplarTraceIdDestinations:
            - name: trace_id
              datasourceUid: jaeger
      - name: Jaeger
        uid: jaeger
        type: jaeger
        access: proxy
        url: http://inner-cosmos-jaeger.inner-cosmos-w3.svc:16686
        jsonData:
          nodeGraph:
            enabled: true
          tracesToMetrics:
            datasourceUid: prometheus
            tags:
              - {key: service.name, value: service}
  dashboards.yaml: |
    apiVersion: 1
    providers:
      - name: inner-cosmos
        orgId: 1
        folder: Inner Cosmos
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards
