CREATE TABLE IF NOT EXISTS tb_memory_embedding (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  memory_id BIGINT NOT NULL,
  model_name VARCHAR(128) NOT NULL,
  model_version VARCHAR(64) NOT NULL,
  source_version INT NOT NULL,
  task_scope VARCHAR(64) DEFAULT 'GENERAL',
  dimensions INT NOT NULL,
  embedding_json TEXT NOT NULL,
  embedding_vector vector(1536),
  status VARCHAR(32) DEFAULT 'ACTIVE',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_memory_embedding_version UNIQUE (memory_id, model_name, model_version, source_version, task_scope),
  CONSTRAINT fk_memory_embedding_memory FOREIGN KEY (memory_id) REFERENCES tb_memory_card(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_memory_embedding_user_model
  ON tb_memory_embedding(user_id, model_name, model_version, status);
