CREATE TABLE IF NOT EXISTS tb_capsule_genome_version (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  capsule_id BIGINT NOT NULL,
  owner_user_id BIGINT NOT NULL,
  version_no INT NOT NULL,
  parent_version_id BIGINT,
  compiler_version VARCHAR(64) NOT NULL,
  status VARCHAR(32) NOT NULL,
  authorization_snapshot_json TEXT NOT NULL,
  compiled_persona_prompt TEXT NOT NULL,
  style_profile_json TEXT,
  context_preview_json TEXT,
  evaluation_json TEXT NOT NULL,
  change_reason VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_capsule_genome_version UNIQUE (capsule_id, version_no),
  CONSTRAINT fk_capsule_genome_capsule FOREIGN KEY (capsule_id) REFERENCES tb_echo_capsule(id) ON DELETE CASCADE,
  CONSTRAINT fk_capsule_genome_parent FOREIGN KEY (parent_version_id) REFERENCES tb_capsule_genome_version(id)
);

CREATE INDEX IF NOT EXISTS idx_capsule_genome_status
  ON tb_capsule_genome_version(capsule_id, status);
CREATE UNIQUE INDEX IF NOT EXISTS uk_capsule_genome_one_active
  ON tb_capsule_genome_version(capsule_id) WHERE status = 'ACTIVE';

ALTER TABLE tb_echo_capsule ADD COLUMN IF NOT EXISTS active_genome_version_id BIGINT;
ALTER TABLE tb_echo_capsule
  ADD CONSTRAINT fk_echo_capsule_active_genome
  FOREIGN KEY (active_genome_version_id) REFERENCES tb_capsule_genome_version(id) ON DELETE SET NULL;
