CREATE TABLE IF NOT EXISTS tb_psychology_skill_run (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  skill_id VARCHAR(100) NOT NULL,
  skill_version VARCHAR(32) NOT NULL,
  locale VARCHAR(16) NOT NULL,
  status VARCHAR(24) NOT NULL,
  risk_tier VARCHAR(8) NOT NULL,
  retention_choice VARCHAR(32) NOT NULL,
  consent_scopes TEXT NOT NULL,
  input_fingerprint VARCHAR(64) NOT NULL,
  result_json TEXT,
  evidence_refs TEXT NOT NULL,
  escalation_code VARCHAR(48),
  revoked_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ck_psychology_skill_run_status CHECK
    (status IN ('COMPLETED','ESCALATED','REVOKED')),
  CONSTRAINT ck_psychology_skill_retention CHECK
    (retention_choice IN ('DISCARD_AFTER_SESSION','SAVE_RESULT','PROFILE_ELIGIBLE'))
);

CREATE INDEX IF NOT EXISTS idx_psychology_skill_run_owner
  ON tb_psychology_skill_run(user_id, created_at DESC);
