CREATE TABLE IF NOT EXISTS tb_data_use_grant (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_user_id BIGINT NOT NULL,
  resource_type VARCHAR(32) NOT NULL,
  resource_id BIGINT NOT NULL,
  resource_version INT NOT NULL,
  purpose VARCHAR(48) NOT NULL,
  consumer_type VARCHAR(32) NOT NULL,
  consumer_id BIGINT NOT NULL,
  grant_version INT NOT NULL,
  parent_grant_id BIGINT,
  status VARCHAR(24) NOT NULL DEFAULT 'ACTIVE',
  consent_source VARCHAR(64) NOT NULL,
  granted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  revoked_at TIMESTAMP NULL,
  revoke_reason VARCHAR(240),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_data_grant_parent FOREIGN KEY (parent_grant_id) REFERENCES tb_data_use_grant(id)
);
CREATE INDEX IF NOT EXISTS idx_data_grant_consumer ON tb_data_use_grant (consumer_type, consumer_id, status);
CREATE INDEX IF NOT EXISTS idx_data_grant_resource ON tb_data_use_grant (resource_type, resource_id, status);

ALTER TABLE tb_authorized_memory_ref ADD COLUMN IF NOT EXISTS data_use_grant_id BIGINT;

INSERT INTO tb_data_use_grant
  (owner_user_id,resource_type,resource_id,resource_version,purpose,consumer_type,consumer_id,
   grant_version,status,consent_source,granted_at,revoked_at,revoke_reason,created_at,updated_at)
SELECT c.owner_user_id,'MEMORY_CARD',m.id,COALESCE(m.version_no,1),
       CASE WHEN COALESCE(c.simulator_only,FALSE) THEN 'CAPSULE_SIMULATOR' ELSE 'CAPSULE_RUNTIME' END,
       'ECHO_CAPSULE',c.id,1,
       CASE WHEN r.authorization_status='AUTHORIZED' THEN 'ACTIVE' ELSE 'REVOKED' END,
       'LEGACY_AUTHORIZED_MEMORY_REF_BACKFILL',COALESCE(r.created_at,CURRENT_TIMESTAMP),
       CASE WHEN r.authorization_status='AUTHORIZED' THEN NULL ELSE COALESCE(r.updated_at,CURRENT_TIMESTAMP) END,
       CASE WHEN r.authorization_status='AUTHORIZED' THEN NULL ELSE 'LEGACY_REF_NOT_ACTIVE' END,
       COALESCE(r.created_at,CURRENT_TIMESTAMP),COALESCE(r.updated_at,CURRENT_TIMESTAMP)
FROM tb_authorized_memory_ref r
JOIN tb_echo_capsule c ON c.id=r.capsule_id
JOIN tb_memory_card m ON m.id=r.memory_card_id
WHERE NOT EXISTS (
  SELECT 1 FROM tb_data_use_grant g WHERE g.consumer_type='ECHO_CAPSULE' AND g.consumer_id=c.id
    AND g.resource_type='MEMORY_CARD' AND g.resource_id=m.id
    AND g.purpose=CASE WHEN COALESCE(c.simulator_only,FALSE) THEN 'CAPSULE_SIMULATOR' ELSE 'CAPSULE_RUNTIME' END
);

INSERT INTO tb_data_use_grant
  (owner_user_id,resource_type,resource_id,resource_version,purpose,consumer_type,consumer_id,
   grant_version,status,consent_source,granted_at,revoked_at,revoke_reason,created_at,updated_at)
SELECT c.owner_user_id,'MEMORY_CARD',m.id,COALESCE(m.version_no,1),'PROVIDER_EGRESS','ECHO_CAPSULE',c.id,1,
       CASE WHEN r.authorization_status='AUTHORIZED' THEN 'ACTIVE' ELSE 'REVOKED' END,
       'LEGACY_AUTHORIZED_MEMORY_REF_BACKFILL',COALESCE(r.created_at,CURRENT_TIMESTAMP),
       CASE WHEN r.authorization_status='AUTHORIZED' THEN NULL ELSE COALESCE(r.updated_at,CURRENT_TIMESTAMP) END,
       CASE WHEN r.authorization_status='AUTHORIZED' THEN NULL ELSE 'LEGACY_REF_NOT_ACTIVE' END,
       COALESCE(r.created_at,CURRENT_TIMESTAMP),COALESCE(r.updated_at,CURRENT_TIMESTAMP)
FROM tb_authorized_memory_ref r
JOIN tb_echo_capsule c ON c.id=r.capsule_id
JOIN tb_memory_card m ON m.id=r.memory_card_id
WHERE NOT EXISTS (
  SELECT 1 FROM tb_data_use_grant g WHERE g.consumer_type='ECHO_CAPSULE' AND g.consumer_id=c.id
    AND g.resource_type='MEMORY_CARD' AND g.resource_id=m.id AND g.purpose='PROVIDER_EGRESS'
);

UPDATE tb_authorized_memory_ref r SET data_use_grant_id = (
  SELECT g.id FROM tb_data_use_grant g
  JOIN tb_echo_capsule c ON c.id=r.capsule_id
  WHERE g.consumer_type='ECHO_CAPSULE' AND g.consumer_id=r.capsule_id
    AND g.resource_type='MEMORY_CARD' AND g.resource_id=r.memory_card_id
    AND g.purpose=CASE WHEN COALESCE(c.simulator_only,FALSE) THEN 'CAPSULE_SIMULATOR' ELSE 'CAPSULE_RUNTIME' END
  ORDER BY g.grant_version DESC LIMIT 1
) WHERE r.data_use_grant_id IS NULL;

ALTER TABLE tb_authorized_memory_ref
  ADD CONSTRAINT fk_auth_mem_grant FOREIGN KEY (data_use_grant_id) REFERENCES tb_data_use_grant(id);
