CREATE TABLE IF NOT EXISTS tb_capsule_embedding (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  capsule_id BIGINT NOT NULL,
  model_name VARCHAR(128) NOT NULL,
  model_version VARCHAR(64) NOT NULL,
  content_hash VARCHAR(64) NOT NULL,
  dimensions INT NOT NULL,
  embedding_json TEXT NOT NULL,
  embedding_vector vector(1536),
  status VARCHAR(32) DEFAULT 'ACTIVE',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_capsule_embedding_version UNIQUE (capsule_id, model_name, model_version, content_hash),
  CONSTRAINT fk_capsule_embedding_capsule FOREIGN KEY (capsule_id) REFERENCES tb_echo_capsule(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_capsule_embedding_model
  ON tb_capsule_embedding(model_name, model_version, status);
