-- G5 PROFILE-PROPAGATION / A5 erasure propagation: auditable, sensitive-payload-free receipts of
-- what a user's data-rights action did to each derivative of their source data. Complements
-- tb_memory_projection_receipt (memory-operation scoped) by covering the consent/erasure path,
-- whose subject can be a memory, a capsule or a data-use grant, and whose derivatives include the
-- capsule matching index (tb_capsule_embedding) that previously had no invalidation hook.
CREATE TABLE IF NOT EXISTS tb_data_retraction_receipt (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  subject_type VARCHAR(32) NOT NULL,
  subject_id BIGINT NOT NULL,
  derivative_type VARCHAR(48) NOT NULL,
  action VARCHAR(24) NOT NULL,
  affected_count INT NOT NULL DEFAULT 0,
  reason VARCHAR(240),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_data_retraction_user
  ON tb_data_retraction_receipt(user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_data_retraction_subject
  ON tb_data_retraction_receipt(subject_type, subject_id);
