CREATE TABLE tb_device_registration (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    installation_id VARCHAR(128) NOT NULL,
    platform VARCHAR(24) NOT NULL,
    transport VARCHAR(24) NOT NULL,
    token_hash VARCHAR(64),
    token_ciphertext TEXT,
    app_version VARCHAR(64) NOT NULL,
    locale VARCHAR(32) NOT NULL,
    timezone VARCHAR(64) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    revoked BOOLEAN NOT NULL DEFAULT FALSE,
    last_seen_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_device_installation UNIQUE (installation_id),
    CONSTRAINT ck_device_transport CHECK (transport IN ('FCM','APNS','LOCAL_EVIDENCE')),
    CONSTRAINT fk_device_registration_user FOREIGN KEY (user_id) REFERENCES tb_user(id) ON DELETE CASCADE
);
CREATE INDEX idx_device_owner_active ON tb_device_registration(user_id, enabled, revoked);

CREATE TABLE tb_push_delivery (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    device_id BIGINT NOT NULL,
    wake_intent_id BIGINT,
    title VARCHAR(160) NOT NULL,
    body TEXT NOT NULL,
    deep_link VARCHAR(512) NOT NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'PENDING',
    attempts INTEGER NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    provider_message_id VARCHAR(256),
    last_error_class VARCHAR(128),
    delivered_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_push_wake_device UNIQUE (wake_intent_id, device_id),
    CONSTRAINT ck_push_status CHECK (status IN ('PENDING','PROCESSING','RETRY','DELIVERED','DEAD')),
    CONSTRAINT fk_push_delivery_user FOREIGN KEY (user_id) REFERENCES tb_user(id) ON DELETE CASCADE,
    CONSTRAINT fk_push_delivery_device FOREIGN KEY (device_id) REFERENCES tb_device_registration(id) ON DELETE CASCADE,
    CONSTRAINT fk_push_delivery_wake_intent FOREIGN KEY (wake_intent_id) REFERENCES tb_wake_intent(id) ON DELETE SET NULL
);
CREATE INDEX idx_push_delivery_due ON tb_push_delivery(status, next_attempt_at, id);
