CREATE TABLE tb_user_identity (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  issuer VARCHAR(255) NOT NULL,
  subject VARCHAR(255) NOT NULL,
  email_snapshot VARCHAR(128),
  last_authenticated_at TIMESTAMP NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_user_identity_issuer_subject UNIQUE (issuer, subject),
  CONSTRAINT fk_user_identity_user FOREIGN KEY (user_id) REFERENCES tb_user(id) ON DELETE CASCADE
);
CREATE INDEX idx_user_identity_user ON tb_user_identity (user_id);
