-- Cross-Pod Aurora delivery takeover. The monotonic lease_token is the fencing authority;
-- lease_owner is diagnostic and lease_expires_at is stored as UTC wall time to match the current
-- application Clock/JDBC convention for new infrastructure timestamps.
ALTER TABLE tb_conversation_turn
  ADD COLUMN IF NOT EXISTS lease_owner VARCHAR(160);

ALTER TABLE tb_conversation_turn
  ADD COLUMN IF NOT EXISTS lease_token BIGINT NOT NULL DEFAULT 0;

ALTER TABLE tb_conversation_turn
  ADD COLUMN IF NOT EXISTS lease_expires_at TIMESTAMP NULL;

CREATE INDEX IF NOT EXISTS idx_conversation_turn_takeover
  ON tb_conversation_turn (status, lease_expires_at, updated_at);

-- Recovery-B stores references and bounded routing metadata only. The original user text remains
-- in the access-controlled dialog-message row and is not copied into a recovery payload.
CREATE TABLE IF NOT EXISTS tb_turn_generation_request (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  turn_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  session_id BIGINT NOT NULL,
  user_message_id BIGINT NOT NULL,
  mode VARCHAR(32) NOT NULL,
  locale VARCHAR(24),
  region VARCHAR(16),
  timezone VARCHAR(64),
  context_version VARCHAR(48) NOT NULL,
  foreground_acknowledgement_sent BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_turn_generation_request UNIQUE (turn_id),
  CONSTRAINT fk_turn_generation_request_turn FOREIGN KEY (turn_id)
    REFERENCES tb_conversation_turn(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_turn_generation_request_owner
  ON tb_turn_generation_request (user_id, turn_id);

CREATE TABLE IF NOT EXISTS tb_turn_deliberation_snapshot (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  turn_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  plan_revision INT NOT NULL,
  status VARCHAR(32) NOT NULL,
  snapshot_json TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_turn_deliberation_revision UNIQUE (turn_id, plan_revision),
  CONSTRAINT fk_turn_deliberation_turn FOREIGN KEY (turn_id)
    REFERENCES tb_conversation_turn(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_turn_deliberation_owner
  ON tb_turn_deliberation_snapshot (user_id, turn_id, plan_revision);
