-- CP-03 (commercial-cn blueprint): server-side metric event store for K1-K3 and G-SAFE/G-TRUST.
--
-- Contract highlights (see docs/commercialization/ledger/metric-dictionary.md):
--   * occurred_at_utc is stored as UTC; anchor_week/anchor_day are precomputed Asia/Shanghai
--     ISO-week / local-date anchors so cross-timezone week windows are stable.
--   * event_key is the natural idempotency key: at-least-once emitters may retry safely.
--   * props is P0-free by construction: MetricEventService enforces a per-metric allowlist of
--     scalar keys; raw dialog/letter/safety text must never land here.
--   * On account deletion, user_id is nulled and props scrubbed (anonymized=true); the row stays
--     so historical denominators do not shrink (user_key = COALESCE(user_id,'anon:'||id)).
CREATE TABLE IF NOT EXISTS tb_commercial_metric_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_key VARCHAR(180) NOT NULL,
    metric_code VARCHAR(64) NOT NULL,
    pathway VARCHAR(16),
    user_id BIGINT,
    occurred_at_utc TIMESTAMP NOT NULL,
    anchor_week VARCHAR(10) NOT NULL,
    anchor_day VARCHAR(10) NOT NULL,
    context_type VARCHAR(32),
    context_id VARCHAR(64),
    dim_a VARCHAR(32),
    dim_b VARCHAR(64),
    props TEXT NOT NULL DEFAULT '{}',
    analysis_consent_version VARCHAR(32) NOT NULL,
    ingest_source VARCHAR(24) NOT NULL DEFAULT 'SERVER_CONFIRMED',
    anonymized BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_commercial_metric_event_key UNIQUE (event_key),
    CONSTRAINT ck_metric_pathway CHECK (pathway IN ('PRIVATE', 'CONNECTED', 'PLATFORM')),
    CONSTRAINT ck_metric_ingest CHECK (ingest_source IN ('SERVER_CONFIRMED', 'BACKFILL'))
);
CREATE INDEX IF NOT EXISTS idx_metric_code_week ON tb_commercial_metric_event (metric_code, anchor_week);
CREATE INDEX IF NOT EXISTS idx_metric_user_code ON tb_commercial_metric_event (user_id, metric_code);
CREATE INDEX IF NOT EXISTS idx_metric_anonymized ON tb_commercial_metric_event (anonymized) WHERE anonymized;

-- Per-user analysis consent gate (CP-03 plumbing; the full consent contract lands with CP-07).
-- Absence of a row means the default policy in MetricEventService applies (granted, v1).
CREATE TABLE IF NOT EXISTS tb_analysis_consent (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    status VARCHAR(16) NOT NULL,
    consent_version VARCHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_analysis_consent_user UNIQUE (user_id),
    CONSTRAINT ck_analysis_consent_status CHECK (status IN ('GRANTED', 'DECLINED'))
);

-- Anonymization rollup: when an account is deleted, its events are removed entirely but
-- per-metric-per-week aggregate counts (and rights affected-record totals) are preserved
-- here so historical denominators never shrink and deleted users stop being tracked
-- individually. K2_ACTIVATION rows keep original cohort sizes ("删号用户保留于原队列").
CREATE TABLE IF NOT EXISTS tb_commercial_metric_rollup (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    metric_code VARCHAR(64) NOT NULL,
    anchor_week VARCHAR(10) NOT NULL,
    anonymized_count BIGINT NOT NULL DEFAULT 0,
    affected_total BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_commercial_metric_rollup UNIQUE (metric_code, anchor_week)
);
