-- CP-08 (commercial-cn blueprint): adult admission gate and minor-intercept state.
--
-- The adult service is 18+ by design; age is captured at registration (self-declared full
-- birth date, Asia/Shanghai reckoning) and upgraded later by CP-13 real identity flows.
-- A discovered minor is moved to MINOR_RESTRICTED: adult companion/social features stop,
-- safety resources stay reachable and a documented appeal path exists (tb_minor_appeal).
ALTER TABLE tb_user ADD COLUMN IF NOT EXISTS birth_date DATE NULL;
ALTER TABLE tb_user ADD COLUMN IF NOT EXISTS age_gate_method VARCHAR(24) NULL;

CREATE TABLE IF NOT EXISTS tb_minor_appeal (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    statement TEXT NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    decided_by BIGINT,
    decision_note VARCHAR(400),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_minor_appeal_status CHECK (status IN ('PENDING', 'ACCEPTED', 'REJECTED'))
);
CREATE INDEX IF NOT EXISTS idx_minor_appeal_user ON tb_minor_appeal (user_id);
CREATE INDEX IF NOT EXISTS idx_minor_appeal_pending ON tb_minor_appeal (status);
