-- CP-07 (commercial-cn blueprint): the consent center record store.
--
-- One row per (user, purpose) holding the latest effective decision plus grant/revoke
-- timestamps. Purpose semantics, grouping and defaults live in ConsentPurpose (code),
-- not in the database. ANALYTICS stays dual-written with tb_analysis_consent so the
-- CP-03 metric gate keeps working; managed purposes (capsule compilation) are surfaced
-- read-only from their existing stores and never rows here.
CREATE TABLE IF NOT EXISTS tb_consent_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    purpose_code VARCHAR(48) NOT NULL,
    status VARCHAR(16) NOT NULL,
    version VARCHAR(32) NOT NULL,
    granted_at TIMESTAMP,
    revoked_at TIMESTAMP,
    evidence_source VARCHAR(64) NOT NULL DEFAULT 'CONSENT_CENTER',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_consent_user_purpose UNIQUE (user_id, purpose_code),
    CONSTRAINT ck_consent_status CHECK (status IN ('GRANTED', 'DECLINED'))
);
CREATE INDEX IF NOT EXISTS idx_consent_user ON tb_consent_record (user_id);
