-- CP-13 (commercial-cn blueprint): VERIFIED_ID age-verification upgrade chain and
-- multi-device account security events.
--
-- tb_identity_verification stores the OUTCOME and provider reference of an age/
-- identity check — never credential images, raw SMS codes or full personal numbers
-- (recovery clause: no ID images in logs; manual recovery stays auditable).
-- A verified birth date under 18 links into the CP-08 minor-intercept state.
CREATE TABLE IF NOT EXISTS tb_identity_verification (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    method VARCHAR(32) NOT NULL,
    provider VARCHAR(48) NOT NULL,
    provider_reference VARCHAR(128) NOT NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'PENDING',
    verified_birth_date DATE,
    failure_reason VARCHAR(200),
    verified_at TIMESTAMP,
    expires_at TIMESTAMP NOT NULL,
    consumed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_identity_verification_reference UNIQUE (provider_reference),
    CONSTRAINT ck_identity_verification_status CHECK (
        status IN ('PENDING', 'VERIFIED', 'REJECTED', 'EXPIRED'))
);
CREATE INDEX IF NOT EXISTS idx_identity_verification_user
    ON tb_identity_verification (user_id, status);

-- Account-security audit trail: device revocations, freezes, verification upgrades.
CREATE TABLE IF NOT EXISTS tb_account_security_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    action VARCHAR(48) NOT NULL,
    actor_id BIGINT,
    detail VARCHAR(400),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_account_security_event_user
    ON tb_account_security_event (user_id, id);
