-- CP-15 (commercial-cn blueprint): retraction tombstones and the rights watermark.
--
-- Business rows can come back from an old backup; the tombstone registry must therefore be
-- logically independent of the business tables: every retraction writes an immutable marker
-- here (same transaction as the receipt), reads consult it before serving any retracted
-- subject, and disaster recovery must catch up to the durable watermark BEFORE reopening.
-- Restoring an old copy of this table alone does not satisfy the blueprint: the watermark
-- ledger has to be provable from the independent retention copy.
CREATE TABLE IF NOT EXISTS tb_retraction_tombstone (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_type VARCHAR(48) NOT NULL,
    subject_id BIGINT NOT NULL,
    owner_user_id BIGINT NOT NULL,
    consent_version VARCHAR(32),
    reason VARCHAR(200),
    applied_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_retraction_tombstone_subject UNIQUE (subject_type, subject_id)
);
CREATE INDEX IF NOT EXISTS idx_retraction_tombstone_owner ON tb_retraction_tombstone (owner_user_id);
