-- CP-20 (commercial-cn blueprint): durable cross-session risk continuity and the crisis
-- intervention ledger.
--
-- SessionRiskAggregator stays as the per-session, in-memory rolling view; THIS state is the
-- cross-session, cross-Pod durable picture with explicit decay. Every escalation step is an
-- auditable intervention row (responsible actor, attempt/outcome, escalation, minimal
-- disclosure) as blueprint 5.2/CP-20 require — never an implicit JVM side effect.
CREATE TABLE IF NOT EXISTS tb_user_risk_state (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    level VARCHAR(16) NOT NULL DEFAULT 'NONE',
    score DOUBLE PRECISION NOT NULL DEFAULT 0,
    last_observed_at TIMESTAMP NOT NULL,
    last_safety_event_id BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_user_risk_state UNIQUE (user_id),
    CONSTRAINT ck_user_risk_level CHECK (level IN ('NONE', 'WATCH', 'ELEVATED'))
);

CREATE TABLE IF NOT EXISTS tb_crisis_intervention (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    safety_event_id BIGINT,
    level VARCHAR(16) NOT NULL,
    action VARCHAR(48) NOT NULL,
    responder_id BIGINT,
    outcome VARCHAR(200),
    escalation VARCHAR(200),
    minimal_disclosure VARCHAR(200),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_crisis_intervention_level CHECK (level IN ('NONE', 'WATCH', 'ELEVATED', 'EMERGENCY')),
    CONSTRAINT ck_crisis_intervention_action CHECK (action IN
        ('GENTLE_CHECK_IN', 'RESOURCES_SHOWN', 'WATCH_ESCALATED', 'EMERGENCY_PROTOCOL'))
);
CREATE INDEX IF NOT EXISTS idx_crisis_intervention_user ON tb_crisis_intervention (user_id, id);
