-- CP-36 (commercial-cn blueprint): the trust-and-safety case backend on top of reports.
-- Every report opens exactly one case with a priority-derived SLA clock; assignment,
-- resolution, appeal and every state change are audited. Moderator views isolate the
-- reporter's identity behind an authorization flag (protect-the-reporter).
CREATE TABLE IF NOT EXISTS tb_moderation_case (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id BIGINT NOT NULL,
    target_type VARCHAR(48) NOT NULL,
    target_id BIGINT NOT NULL,
    priority VARCHAR(4) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'OPEN',
    assignee_id BIGINT,
    sla_due_at TIMESTAMP NOT NULL,
    resolution VARCHAR(400),
    appeal_note VARCHAR(400),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_moderation_case_report UNIQUE (report_id),
    CONSTRAINT ck_moderation_case_priority CHECK (priority IN ('P0', 'P1', 'P2')),
    CONSTRAINT ck_moderation_case_status CHECK (status IN
        ('OPEN', 'ASSIGNED', 'RESOLVED', 'DISMISSED', 'APPEALED'))
);
CREATE INDEX IF NOT EXISTS idx_moderation_case_queue ON tb_moderation_case (status, priority, sla_due_at);
