-- CP-47 (commercial-cn blueprint): append-only payment event ledger. Callback facts are
-- recorded idempotently per provider_event_id; reconciliation nets payments minus refunds
-- per order (order-insensitive by construction, so out-of-order callbacks cannot corrupt
-- the math). NO amounts, signatures or provider secrets beyond these minimal columns.
CREATE TABLE IF NOT EXISTS tb_payment_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_event_id VARCHAR(128) NOT NULL,
    provider VARCHAR(32) NOT NULL,
    order_id VARCHAR(64) NOT NULL,
    event_type VARCHAR(24) NOT NULL,
    amount_cents BIGINT NOT NULL,
    currency CHAR(3) NOT NULL DEFAULT 'CNY',
    status VARCHAR(16) NOT NULL DEFAULT 'RECORDED',
    occurred_at TIMESTAMP NOT NULL,
    received_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_payment_event_provider_event UNIQUE (provider_event_id),
    CONSTRAINT ck_payment_event_type CHECK (event_type IN ('PAYMENT_SUCCEEDED', 'REFUND_SUCCEEDED')),
    CONSTRAINT ck_payment_event_status CHECK (status IN ('RECORDED', 'RECONCILED', 'DISPUTED')),
    CONSTRAINT ck_payment_event_amount_positive CHECK (amount_cents > 0)
);
CREATE INDEX IF NOT EXISTS idx_payment_event_order ON tb_payment_event (order_id, event_type);
