-- CP-46 (commercial-cn blueprint): unified server-side entitlement state machine over the
-- append-only payment ledger. One row per (user, product) regardless of channel — the
-- unified state (PENDING_PAYMENT/TRIAL/ACTIVE/GRACE_PERIOD/CANCELLED/EXPIRED/REVOKED) is
-- the only thing product code may read; channel-original states live in the transition
-- audit below. tb_entitlement_event gives notification dedup (a duplicated channel
-- notification acks, never double-transitions) and the 退款后撤销/恢复购买 audit trail.
CREATE TABLE IF NOT EXISTS tb_entitlement (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    product_id VARCHAR(64) NOT NULL,
    channel VARCHAR(32) NOT NULL,
    channel_order_id VARCHAR(64),
    state VARCHAR(24) NOT NULL,
    period_start TIMESTAMP NOT NULL,
    period_end TIMESTAMP NOT NULL,
    auto_renew BOOLEAN NOT NULL DEFAULT TRUE,
    cancel_at_period_end BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_entitlement_user_product UNIQUE (user_id, product_id),
    CONSTRAINT ck_entitlement_state CHECK (state IN
        ('PENDING_PAYMENT', 'TRIAL', 'ACTIVE', 'GRACE_PERIOD', 'CANCELLED', 'EXPIRED', 'REVOKED'))
);
CREATE INDEX IF NOT EXISTS idx_entitlement_user ON tb_entitlement (user_id, state);

CREATE TABLE IF NOT EXISTS tb_entitlement_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_notification_id VARCHAR(128) NOT NULL,
    entitlement_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    transition VARCHAR(48) NOT NULL,
    from_state VARCHAR(24) NOT NULL,
    to_state VARCHAR(24) NOT NULL,
    occurred_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_entitlement_event_notification UNIQUE (channel_notification_id)
);
CREATE INDEX IF NOT EXISTS idx_entitlement_event_entitlement ON tb_entitlement_event (entitlement_id);
