-- CP-45 (commercial-cn blueprint): server-side order catalog. The expected amount,
-- product and channel for every order the app itself created — the authority the
-- callback pipeline validates channel claims against (服务端校验订单/金额/渠道; a correctly
-- signed callback for an amount we never asked for is drift, not a fact to absorb).
-- Payment state is NOT stored here: it lives in the append-only tb_payment_event ledger.
CREATE TABLE IF NOT EXISTS tb_payment_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id VARCHAR(64) NOT NULL,
    user_id BIGINT NOT NULL,
    product_id VARCHAR(64) NOT NULL,
    channel VARCHAR(32) NOT NULL,
    expected_amount_cents BIGINT NOT NULL,
    currency CHAR(3) NOT NULL DEFAULT 'CNY',
    status VARCHAR(16) NOT NULL DEFAULT 'CREATED',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_payment_order_order_id UNIQUE (order_id),
    CONSTRAINT ck_payment_order_amount_positive CHECK (expected_amount_cents > 0),
    CONSTRAINT ck_payment_order_status CHECK (status IN ('CREATED', 'CLOSED'))
);
CREATE INDEX IF NOT EXISTS idx_payment_order_user ON tb_payment_order (user_id, product_id);
