-- CP-62 (commercial-cn blueprint): data portability import receipts. The migration
-- roundtrip (蓝图 L893) requires idempotent re-import: every imported source record is
-- receipted by its natural key (section + source record id), so a repeated import of the
-- same package inserts nothing. Receipts are facts only — no entity state lives here.
CREATE TABLE IF NOT EXISTS tb_data_import_receipt (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_user_id BIGINT NOT NULL,
    source_user_id BIGINT NOT NULL,
    section VARCHAR(48) NOT NULL,
    source_record_key VARCHAR(160) NOT NULL,
    imported_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_data_import_natural_key UNIQUE (section, source_record_key, target_user_id)
);
CREATE INDEX IF NOT EXISTS idx_data_import_target ON tb_data_import_receipt (target_user_id, imported_at);
