-- CP-35 group governance (closing-checklist §2-7): mute / ownership transfer / dissolve /
-- join-time-bounded history visibility / per-group host review capacity ledger.
--
-- Governance role decision: "主持人" (host) is the group OWNER. No separate MODERATOR member
-- role is introduced in this batch -- without an appointment lifecycle it would be dead
-- vocabulary, so every host-gated action (mute, unmute, transfer, dissolve, review
-- resolution) checks group.owner_user_id.
ALTER TABLE tb_social_group ADD COLUMN IF NOT EXISTS status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE';
ALTER TABLE tb_social_group DROP CONSTRAINT IF EXISTS ck_social_group_status;
ALTER TABLE tb_social_group ADD CONSTRAINT ck_social_group_status
    CHECK (status IN ('ACTIVE', 'DISSOLVED'));

-- joined_at is the join instant for history visibility: the member row itself is created at
-- invite time (status PENDING), so created_at would leak pre-join history to late acceptors.
-- muted_at NULL = not muted; muted_at set + muted_until NULL = muted until manual release.
ALTER TABLE tb_social_group_member ADD COLUMN IF NOT EXISTS joined_at TIMESTAMP;
ALTER TABLE tb_social_group_member ADD COLUMN IF NOT EXISTS muted_at TIMESTAMP;
ALTER TABLE tb_social_group_member ADD COLUMN IF NOT EXISTS muted_until TIMESTAMP;
ALTER TABLE tb_social_group_member ADD COLUMN IF NOT EXISTS muted_by BIGINT;

-- Structured per-group review ledger (capacity gate input). Capacity semantics: the number
-- of status='PENDING' rows per group is bounded by
-- inner-cosmos.social.group-review-pending-capacity (default 20); once the bound is reached
-- NEW reports are explicitly REJECTED (honest fail-closed error, nothing silently queued,
-- nothing silently dropped). OVER-capacity is therefore never representable in this table:
-- no PENDING_OVERFLOW state exists on purpose.
CREATE TABLE IF NOT EXISTS tb_group_review_ledger (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id BIGINT NOT NULL,
  reporter_user_id BIGINT NOT NULL,
  target_user_id BIGINT,
  target_message_id BIGINT,
  reason VARCHAR(400) NOT NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
  resolution_note VARCHAR(400),
  resolved_by BIGINT,
  resolved_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ck_group_review_status CHECK (status IN ('PENDING', 'RESOLVED', 'DISMISSED'))
);
CREATE INDEX IF NOT EXISTS idx_group_review_pending ON tb_group_review_ledger (group_id, status);
