-- CP-34: both-party-consent relation corrections on shared letter threads.
-- A thread's relationship understanding is built from BOTH parties' data, so one side
-- cannot rewrite it alone: corrections live as proposals until the counterpart accepts.
CREATE TABLE tb_relation_correction (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  thread_id BIGINT NOT NULL,
  proposer_user_id BIGINT NOT NULL,
  counterpart_user_id BIGINT NOT NULL,
  correction_field VARCHAR(64) NOT NULL,
  proposed_value TEXT NOT NULL,
  note TEXT,
  status VARCHAR(16) NOT NULL DEFAULT 'PROPOSED',
  decision_reason TEXT,
  decided_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_relation_correction_thread FOREIGN KEY (thread_id) REFERENCES tb_letter_thread (id),
  CONSTRAINT ck_relation_correction_status CHECK (status IN ('PROPOSED', 'APPLIED', 'REJECTED', 'WITHDRAWN'))
);
CREATE INDEX idx_relation_correction_counterpart ON tb_relation_correction (counterpart_user_id, status);
