-- CP-18 closing-checklist §2-13: the owner's withdrawal switch for VISIBLE cross-session
-- continuity. One row per user; absence of a row = the default OPEN state.
--   opening_visible = TRUE  (default) the opening card supply endpoint serves the honest
--                                prior-session carry-forward as before;
--   opening_visible = FALSE the supply endpoint returns an explicit "withdrawn" marker with
--                                zero prior material, while continuity FACTS (summaries,
--                                memory settlement) keep being recorded unchanged — hiding
--                                the card is a display choice, never a fabricated
--                                "nothing ever happened".
CREATE TABLE tb_continuity_preference (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  opening_visible BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_continuity_preference_user UNIQUE (user_id)
);
