-- CP-45 final residual (§2-21, payments half): immutable price versions + order expiry.
--
-- Pricing authority moves from the hardcoded sandbox constant to an append-only price
-- version table: a price change is a NEW ACTIVE row plus the old row flipping to RETIRED
-- (改价=新版本行) — amounts are never edited in place, so every order can always trace
-- back to the exact version (and amount) it was priced at. The partial unique index
-- keeps exactly one ACTIVE version per product at any time.
CREATE TABLE IF NOT EXISTS tb_price_version (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id VARCHAR(64) NOT NULL,
    version INT NOT NULL,
    amount_cents BIGINT NOT NULL,
    currency CHAR(3) NOT NULL DEFAULT 'CNY',
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    effective_from TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    retired_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_price_version_product_version UNIQUE (product_id, version),
    CONSTRAINT ck_price_version_amount_positive CHECK (amount_cents > 0),
    CONSTRAINT ck_price_version_status CHECK (status IN ('ACTIVE', 'RETIRED'))
);
-- Exactly one ACTIVE version per product. H2 has no partial indexes, so the schema.sql
-- twin enforces this in the service layer only (PostgreSQL carries the hard guarantee).
CREATE UNIQUE INDEX IF NOT EXISTS uq_price_version_product_active
    ON tb_price_version (product_id) WHERE status = 'ACTIVE';

-- Orders pin the price version they were created under and carry an expiry deadline:
-- an order nobody paid within its TTL is EXPIRED — a terminal state. A late callback
-- for an expired order is refused as a fact (never fabricated into a success) and stays
-- visible for reconciliation. Legacy rows keep NULL expires_at = never expires.
ALTER TABLE tb_payment_order
    ADD COLUMN price_version_id BIGINT,
    ADD COLUMN expires_at TIMESTAMP;
ALTER TABLE tb_payment_order
    ADD CONSTRAINT fk_payment_order_price_version FOREIGN KEY (price_version_id)
        REFERENCES tb_price_version (id);
ALTER TABLE tb_payment_order DROP CONSTRAINT ck_payment_order_status;
ALTER TABLE tb_payment_order
    ADD CONSTRAINT ck_payment_order_status CHECK (status IN ('CREATED', 'CLOSED', 'EXPIRED'));
CREATE INDEX IF NOT EXISTS idx_payment_order_expiry
    ON tb_payment_order (status, expires_at);

-- The ledger gains one informational fact type + one status for refused late callbacks:
-- EXPIRED_ORDER_CALLBACK rows never enter the net (payments minus refunds) — they exist
-- so a channel that paid an order we already expired stays visible for ops 对账.
ALTER TABLE tb_payment_event DROP CONSTRAINT ck_payment_event_type;
ALTER TABLE tb_payment_event
    ADD CONSTRAINT ck_payment_event_type CHECK (event_type IN (
        'PAYMENT_SUCCEEDED', 'REFUND_SUCCEEDED', 'EXPIRED_ORDER_CALLBACK'));
ALTER TABLE tb_payment_event DROP CONSTRAINT ck_payment_event_status;
ALTER TABLE tb_payment_event
    ADD CONSTRAINT ck_payment_event_status CHECK (status IN (
        'RECORDED', 'RECONCILED', 'DISPUTED', 'REJECTED'));
