ALTER TABLE tb_aurora_self_model DROP CONSTRAINT IF EXISTS uk_self_model_user_dim;
CREATE UNIQUE INDEX IF NOT EXISTS uk_self_model_active_dimension
  ON tb_aurora_self_model (user_id, dimension) WHERE status = 'active';
CREATE INDEX IF NOT EXISTS idx_self_model_user_dim
  ON tb_aurora_self_model (user_id, dimension);

ALTER TABLE tb_user_profile ADD COLUMN IF NOT EXISTS timezone VARCHAR(64) NOT NULL DEFAULT 'Asia/Singapore';

CREATE TABLE IF NOT EXISTS tb_aurora_self_version (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  version_no INT NOT NULL,
  parent_version_id BIGINT,
  rollback_target_version_id BIGINT,
  source_proposal_id BIGINT,
  genome_json TEXT NOT NULL,
  constitution_hash VARCHAR(80) NOT NULL,
  public_narrative TEXT NOT NULL,
  status VARCHAR(24) NOT NULL CHECK (status IN ('ACTIVE','RETIRED')),
  activated_at TIMESTAMP,
  retired_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_self_version_user_no UNIQUE (user_id, version_no)
);
CREATE INDEX IF NOT EXISTS idx_self_version_user_status ON tb_aurora_self_version (user_id, status);

CREATE TABLE IF NOT EXISTS tb_emergence_proposal (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  source_reflection_id BIGINT NOT NULL,
  dimension VARCHAR(64) NOT NULL,
  current_belief TEXT,
  proposed_belief TEXT NOT NULL,
  evidence_refs TEXT NOT NULL,
  counter_evidence_json TEXT NOT NULL,
  expected_impact_json TEXT NOT NULL,
  changes_constitution BOOLEAN NOT NULL DEFAULT FALSE,
  rollback_target_version_id BIGINT,
  policy_version VARCHAR(64) NOT NULL,
  status VARCHAR(24) NOT NULL CHECK (status IN ('DRAFT','EVALUATED','ACTIVATED','REJECTED')),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_emergence_proposal_user_status ON tb_emergence_proposal (user_id, status);

CREATE TABLE IF NOT EXISTS tb_emergence_evaluation (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  proposal_id BIGINT NOT NULL,
  evaluator_version VARCHAR(64) NOT NULL,
  constitution_pass BOOLEAN NOT NULL,
  safety_pass BOOLEAN NOT NULL,
  fidelity_score DOUBLE PRECISION NOT NULL,
  quality_score DOUBLE PRECISION NOT NULL,
  continuity_score DOUBLE PRECISION NOT NULL,
  decision VARCHAR(16) NOT NULL CHECK (decision IN ('PASS','FAIL')),
  reasons_json TEXT NOT NULL,
  sandbox_before TEXT NOT NULL,
  sandbox_after TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_emergence_eval_proposal ON tb_emergence_evaluation (proposal_id, created_at);
