ALTER TABLE tb_user_correction
  ADD COLUMN IF NOT EXISTS status VARCHAR(32) DEFAULT 'CONFIRMED',
  ADD COLUMN IF NOT EXISTS impact_summary TEXT,
  ADD COLUMN IF NOT EXISTS confirmed_at TIMESTAMP NULL,
  ADD COLUMN IF NOT EXISTS retired_at TIMESTAMP NULL;

UPDATE tb_user_correction SET status = 'CONFIRMED' WHERE status IS NULL;

CREATE TABLE IF NOT EXISTS tb_understanding_claim (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  claim_key VARCHAR(192) NOT NULL,
  claim_type VARCHAR(32) NOT NULL,
  value_json TEXT NOT NULL,
  authority_level VARCHAR(32) NOT NULL,
  confidence DOUBLE PRECISION DEFAULT 0,
  status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
  source_type VARCHAR(32),
  source_id BIGINT,
  version INT NOT NULL,
  supersedes_claim_id BIGINT,
  correction_id BIGINT,
  evidence_refs TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_understanding_claim_version UNIQUE (user_id, claim_key, version),
  CONSTRAINT fk_claim_previous FOREIGN KEY (supersedes_claim_id) REFERENCES tb_understanding_claim(id) ON DELETE SET NULL,
  CONSTRAINT fk_claim_correction FOREIGN KEY (correction_id) REFERENCES tb_user_correction(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_understanding_claim_current
  ON tb_understanding_claim(user_id, status);

CREATE TABLE IF NOT EXISTS tb_claim_propagation (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  correction_id BIGINT NOT NULL,
  claim_id BIGINT NOT NULL,
  target_kind VARCHAR(48) NOT NULL,
  target_id BIGINT,
  status VARCHAR(32) NOT NULL,
  detail TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_propagation_correction FOREIGN KEY (correction_id) REFERENCES tb_user_correction(id) ON DELETE CASCADE,
  CONSTRAINT fk_propagation_claim FOREIGN KEY (claim_id) REFERENCES tb_understanding_claim(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_claim_propagation_correction
  ON tb_claim_propagation(user_id, correction_id);
