ALTER TABLE tb_memory_card
  ADD COLUMN IF NOT EXISTS version_no INT DEFAULT 1,
  ADD COLUMN IF NOT EXISTS memory_layer VARCHAR(32) DEFAULT 'EPISODIC',
  ADD COLUMN IF NOT EXISTS confidence DOUBLE PRECISION DEFAULT 0.5,
  ADD COLUMN IF NOT EXISTS consent_scope VARCHAR(32) DEFAULT 'AURORA_PRIVATE',
  ADD COLUMN IF NOT EXISTS superseded_by_id BIGINT,
  ADD COLUMN IF NOT EXISTS provenance_refs TEXT,
  ADD COLUMN IF NOT EXISTS archived_at TIMESTAMP NULL,
  ADD COLUMN IF NOT EXISTS forgotten_at TIMESTAMP NULL;

UPDATE tb_memory_card SET version_no=1 WHERE version_no IS NULL;
UPDATE tb_memory_card SET memory_layer='EPISODIC' WHERE memory_layer IS NULL;
UPDATE tb_memory_card SET consent_scope='AURORA_PRIVATE' WHERE consent_scope IS NULL;

CREATE TABLE IF NOT EXISTS tb_memory_operation (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  operation_type VARCHAR(32) NOT NULL,
  primary_memory_id BIGINT,
  related_memory_ids TEXT,
  old_version INT,
  new_version INT,
  before_snapshot JSONB,
  after_snapshot JSONB,
  evidence_refs TEXT,
  model_name VARCHAR(128),
  prompt_version VARCHAR(64),
  reason_code VARCHAR(128),
  confidence DOUBLE PRECISION,
  actor_type VARCHAR(32) NOT NULL,
  rollback_of_operation_id BIGINT,
  status VARCHAR(32) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_memory_operation_rollback FOREIGN KEY (rollback_of_operation_id) REFERENCES tb_memory_operation(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_memory_operation_user ON tb_memory_operation(user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_memory_operation_primary ON tb_memory_operation(user_id, primary_memory_id);

CREATE TABLE IF NOT EXISTS tb_memory_link (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  source_memory_id BIGINT NOT NULL,
  target_memory_id BIGINT NOT NULL,
  link_type VARCHAR(32) NOT NULL,
  strength DOUBLE PRECISION DEFAULT 0.5,
  evidence_refs TEXT,
  status VARCHAR(32) DEFAULT 'ACTIVE',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_memory_link UNIQUE (user_id, source_memory_id, target_memory_id, link_type),
  CONSTRAINT fk_memory_link_source FOREIGN KEY (source_memory_id) REFERENCES tb_memory_card(id) ON DELETE CASCADE,
  CONSTRAINT fk_memory_link_target FOREIGN KEY (target_memory_id) REFERENCES tb_memory_card(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_memory_link_source ON tb_memory_link(user_id, source_memory_id);
CREATE INDEX IF NOT EXISTS idx_memory_link_target ON tb_memory_link(user_id, target_memory_id);
