CREATE TABLE IF NOT EXISTS tb_memory_projection_receipt (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  operation_id BIGINT NOT NULL,
  projection_type VARCHAR(32) NOT NULL,
  status VARCHAR(32) NOT NULL,
  generation INT DEFAULT 1,
  detail TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_memory_projection_receipt UNIQUE (operation_id, projection_type),
  CONSTRAINT fk_memory_projection_operation FOREIGN KEY (operation_id) REFERENCES tb_memory_operation(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_memory_projection_user
  ON tb_memory_projection_receipt(user_id, created_at);
