param(
    [string]$Source = "src/main/resources/schema.sql",
    [string]$Destination = "src/main/resources/db/migration/postgresql/V1__application_baseline.sql"
)

$ErrorActionPreference = "Stop"
$sourcePath = (Resolve-Path -LiteralPath $Source).Path
$destinationPath = [System.IO.Path]::GetFullPath((Join-Path (Get-Location) $Destination))
$lines = [System.IO.File]::ReadAllLines($sourcePath, [System.Text.Encoding]::UTF8)
$output = [System.Collections.Generic.List[string]]::new()
$indexes = [System.Collections.Generic.List[string]]::new()
$tableBody = [System.Collections.Generic.List[string]]::new()
$tableName = $null

$output.Add("-- Generated deterministically from src/main/resources/schema.sql.")
$output.Add("-- Regenerate with scripts/convert-schema-to-postgres.ps1 and review the diff.")
$output.Add("CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;")
$output.Add("")

function Convert-TypeSyntax([string]$line) {
    $converted = $line -replace '\bAUTO_INCREMENT\b', 'GENERATED BY DEFAULT AS IDENTITY'
    $converted = $converted -replace '\bDOUBLE\b(?!\s+PRECISION)', 'DOUBLE PRECISION'
    return $converted
}

function Flush-Table {
    if ($null -eq $script:tableName) { return }

    $retained = [System.Collections.Generic.List[string]]::new()
    foreach ($bodyLine in $script:tableBody) {
        if ($bodyLine -match '^\s*INDEX\s+([A-Za-z0-9_]+)\s*\((.+)\)\s*,?\s*$') {
            $script:indexes.Add("CREATE INDEX IF NOT EXISTS $($Matches[1]) ON $script:tableName ($($Matches[2]));")
            continue
        }
        if ($bodyLine -match '^\s*UNIQUE\s+(?:KEY|INDEX)\s+([A-Za-z0-9_]+)\s*\((.+)\)\s*,?\s*$') {
            $retained.Add("  CONSTRAINT $($Matches[1]) UNIQUE ($($Matches[2])),")
            continue
        }
        $retained.Add((Convert-TypeSyntax $bodyLine))
    }

    for ($index = $retained.Count - 1; $index -ge 0; $index--) {
        if ($retained[$index].Trim().Length -eq 0 -or $retained[$index].TrimStart().StartsWith('--')) { continue }
        $retained[$index] = $retained[$index] -replace ',\s*$', ''
        break
    }

    $script:output.Add("CREATE TABLE IF NOT EXISTS $script:tableName (")
    foreach ($line in $retained) { $script:output.Add($line) }
    $script:output.Add(");")
    foreach ($indexSql in $script:indexes) { $script:output.Add($indexSql) }
    $script:output.Add("")

    $script:tableName = $null
    $script:tableBody.Clear()
    $script:indexes.Clear()
}

foreach ($line in $lines) {
    if ($null -eq $tableName) {
        if ($line -match '^CREATE TABLE IF NOT EXISTS\s+([A-Za-z0-9_]+)\s*\($') {
            $tableName = $Matches[1]
            continue
        }
        $output.Add($line)
        continue
    }

    if ($line -match '^\);\s*$') {
        Flush-Table
        continue
    }
    $tableBody.Add($line)
}

if ($null -ne $tableName) {
    throw "Unterminated CREATE TABLE for $tableName"
}

while ($output.Count -gt 0 -and $output[$output.Count - 1].Length -eq 0) {
    $output.RemoveAt($output.Count - 1)
}

$directory = [System.IO.Path]::GetDirectoryName($destinationPath)
[System.IO.Directory]::CreateDirectory($directory) | Out-Null
$utf8WithoutBom = [System.Text.UTF8Encoding]::new($false)
[System.IO.File]::WriteAllLines($destinationPath, $output, $utf8WithoutBom)
Write-Host "Generated PostgreSQL Flyway baseline: $destinationPath"
