import type { Locale } from "../i18n";
import type { AuroraRuntimeSignal } from "../hooks/useAuroraSession";

type ResponseSource = NonNullable<AuroraRuntimeSignal["responseSource"]>;
type Diagnostics = NonNullable<AuroraRuntimeSignal["diagnostics"]>;

const COPY: Record<Locale, {
  info: string;
  team: string;
  labels: Record<ResponseSource, string>;
  descriptions: Record<ResponseSource, string>;
  fields: Record<keyof Omit<Diagnostics, "stageLatenciesMs"> | "stageLatenciesMs", string>;
}> = {
  "zh-CN": {
    info: "回应来源信息",
    team: "团队诊断",
    labels: {
      REAL_MODEL: "真实模型回应",
      DEMO_MODE: "演示模式",
      BASIC_RESPONSE: "暂时使用基础回应",
      UNKNOWN: "回应来源待确认"
    },
    descriptions: {
      REAL_MODEL: "这次回应由已连接的模型生成。",
      DEMO_MODE: "当前是可持续辨认的演示体验，内容不冒充真实模型调用。",
      BASIC_RESPONSE: "真实模型暂时没有完成这次回应，Aurora 已明确切换到基础回应。",
      UNKNOWN: "这次回应的来源信息尚未完整送达。"
    },
    fields: {
      provider: "Provider",
      model: "Model",
      foregroundSource: "前台来源",
      plannerStatus: "Planner 状态",
      guidanceSource: "Guidance 来源",
      fallbackReason: "Fallback 原因",
      stageLatenciesMs: "阶段耗时"
    }
  },
  "en-SG": {
    info: "Response source information",
    team: "Team diagnostics",
    labels: {
      REAL_MODEL: "Live model response",
      DEMO_MODE: "Demo mode",
      BASIC_RESPONSE: "Using a basic response for now",
      UNKNOWN: "Response source pending"
    },
    descriptions: {
      REAL_MODEL: "This response was generated by the connected model.",
      DEMO_MODE: "This is a clearly marked demo experience and does not pretend a live model was called.",
      BASIC_RESPONSE: "The live model did not complete this response, so Aurora has clearly switched to a basic response.",
      UNKNOWN: "The source details for this response have not arrived in full."
    },
    fields: {
      provider: "Provider",
      model: "Model",
      foregroundSource: "Foreground source",
      plannerStatus: "Planner status",
      guidanceSource: "Guidance source",
      fallbackReason: "Fallback reason",
      stageLatenciesMs: "Stage latency"
    }
  }
};

function textRows(diagnostics: Diagnostics): Array<[keyof Omit<Diagnostics, "stageLatenciesMs">, string]> {
  return ([
    ["provider", diagnostics.provider],
    ["model", diagnostics.model],
    ["foregroundSource", diagnostics.foregroundSource],
    ["plannerStatus", diagnostics.plannerStatus],
    ["guidanceSource", diagnostics.guidanceSource],
    ["fallbackReason", diagnostics.fallbackReason]
  ] as Array<[keyof Omit<Diagnostics, "stageLatenciesMs">, string | undefined]>)
    .filter((row): row is [keyof Omit<Diagnostics, "stageLatenciesMs">, string] => Boolean(row[1]));
}

export function AuroraRuntimeDisclosure({ signal, locale = "zh-CN" }: {
  signal: AuroraRuntimeSignal;
  locale?: Locale;
}) {
  if (!signal.responseSource && !signal.diagnostics) return null;
  const source = signal.responseSource ?? "UNKNOWN";
  const diagnostics = signal.diagnostics ?? {};
  const stages = Object.entries(diagnostics.stageLatenciesMs ?? {});
  const rows = textRows(diagnostics);
  const t = COPY[locale];

  return <details className={`aurora-runtime-disclosure ${source.toLowerCase()}`}>
    <summary aria-label={t.info}>
      <span className="aurora-runtime-source-dot" aria-hidden="true" />
      <span>{t.labels[source]}</span>
    </summary>
    <p>{t.descriptions[source]}</p>
    {(rows.length > 0 || stages.length > 0) && <section aria-label={t.team}>
      <strong>{t.team}</strong>
      <dl>
        {rows.map(([key, value]) => <div key={key}>
          <dt>{t.fields[key]}</dt><dd>{value}</dd>
        </div>)}
        {stages.length > 0 && <div>
          <dt>{t.fields.stageLatenciesMs}</dt>
          <dd>{stages.map(([stage, milliseconds]) => `${stage} ${milliseconds}ms`).join(" · ")}</dd>
        </div>}
      </dl>
    </section>}
  </details>;
}
